# Generated by Django 4.2.3 on 2023-07-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('bill_date', models.DateField()),
                ('from_field', models.CharField(max_length=150)),
                ('to_field', models.CharField(max_length=150)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_address_line_1', models.TextField(max_length=150)),
                ('customer_address_line_2', models.TextField(blank=True, max_length=150)),
                ('customer_address_line_3', models.TextField(blank=True, max_length=150)),
                ('lr_no', models.CharField(max_length=150)),
                ('lr_date', models.DateField()),
                ('invoice_no', models.CharField(max_length=150)),
                ('truck_no', models.CharField(max_length=150)),
                ('container_no', models.CharField(max_length=150)),
                ('be_no', models.CharField(max_length=150)),
                ('freight_charges', models.IntegerField(default=0)),
                ('hamali_charges', models.IntegerField(default=0)),
                ('halting_charges', models.IntegerField(default=0)),
                ('weight_charges', models.IntegerField(default=0)),
                ('bill_exchange_charges', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
    ]
